### ISSUE TITLE
Only error messages

### ISSUE THREAD

**Issue by XiNaru** [HoshiKurama/TicketManager#35] opened 2024-01-11 15:27 UTC
Hey, iam on vbersion 1.18.2 and i have the latest ticketmanager and core plugin AND the addon for mysql.

but i only get error in the console

https://images.xinaru.de/index.php/s/jkqzMoqpFZDgZKW/preview

**Comment by HoshiKurama** [comment] 2024-01-11 15:30
Hey there! It seems whatever platform you’re using doesn’t include Kyori Adventure. Try the Spigot version of TM:SE and let me know how that works for you.

**Comment by XiNaru** [comment] 2024-01-11 15:47
well i had download the paper version because i use paper spigot lol..

but okay i can try it.

**Comment by XiNaru** [comment] 2024-01-11 15:51
okay and NOW..the folder in the plugin folder created BUT ingame there is NO /ticket command anymore...

**Comment by XiNaru** [comment] 2024-01-11 15:55
okay also the log...
1. https://images.xinaru.de/index.php/s/bwGY4bXSyCiy9nE/preview
what? why 11.0.0? i have 11.0.1 from the core


2.


[16:49:04] [DefaultDispatcher-worker-1/WARN]: com.github.hoshikurama.ticketmanager.shaded.kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=JobImpl{Cancelling}@669f034
[16:49:04] [DefaultDispatcher-worker-1/WARN]: Caused by: java.lang.LinkageError: loader constraint violation in interface itable initialization for class com.github.hoshikurama.ticketmanager.spigot.impls.PlatformFunctionsImpl: when selecting method 'void com.github.hoshikurama.ticketmanager.api.PlatformFunctions.massNotify(java.lang.String, net.kyori.adventure.text.Component)' the class loader org.bukkit.plugin.java.PluginClassLoader @26aaf293 for super interface com.github.hoshikurama.ticketmanager.api.PlatformFunctions, and the class loader org.bukkit.plugin.java.PluginClassLoader @6113a2c of the selected method's class, com.github.hoshikurama.ticketmanager.spigot.impls.PlatformFunctionsImpl have different Class objects for the type net.kyori.adventure.text.Component used in the signature (com.github.hoshikurama.ticketmanager.api.PlatformFunctions is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @26aaf293, parent loader java.net.URLClassLoader @4c0df1cf; com.github.hoshikurama.ticketmanager.spigot.impls.PlatformFunctionsImpl is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @6113a2c, parent loader java.net.URLClassLoader @4c0df1cf)
[16:49:04] [DefaultDispatcher-worker-1/WARN]: 	at com.github.hoshikurama.ticketmanager.spigot.impls.TMPluginImpl._init_$lambda$0(TMPluginImpl.kt:44)
[16:49:04] [DefaultDispatcher-worker-1/WARN]: 	at com.github.hoshikurama.ticketmanager.commonse.TMPlugin.enableTicketManager(TMPlugin.kt:84)
[16:49:04] [DefaultDispatcher-worker-1/WARN]: 	at com.github.hoshikurama.ticketmanager.commonse.TMPlugin$enableTicketManager$1.invokeSuspend(TMPlugin.kt)
[16:49:04] [DefaultDispatcher-worker-1/WARN]: 	at com.github.hoshikurama.ticketmanager.shaded.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[16:49:04] [DefaultDispatcher-worker-1/WARN]: 	at com.github.hoshikurama.ticketmanager.shaded.kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
[16:49:04] [DefaultDispatcher-worker-1/WARN]: 	at com.github.hoshikurama.ticketmanager.shaded.kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
[16:49:04] [DefaultDispatcher-worker-1/WARN]: 	at com.github.hoshikurama.ticketmanager.shaded.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
[16:49:04] [DefaultDispatcher-worker-1/WARN]: 	at com.github.hoshikurama.ticketmanager.shaded.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
[16:49:04] [DefaultDispatcher-worker-1/WARN]: 	at com.github.hoshikurama.ticketmanager.shaded.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
[16:49:04] [DefaultDispatcher-worker-2/WARN]: Exception in thread "DefaultDispatcher-worker-2" java.lang.LinkageError: loader constraint violation in interface itable initialization for class com.github.hoshikurama.ticketmanager.spigot.impls.PlatformFunctionsImpl: when selecting method 'void com.github.hoshikurama.ticketmanager.api.PlatformFunctions.massNotify(java.lang.String, net.kyori.adventure.text.Component)' the class loader org.bukkit.plugin.java.PluginClassLoader @26aaf293 for super interface com.github.hoshikurama.ticketmanager.api.PlatformFunctions, and the class loader org.bukkit.plugin.java.PluginClassLoader @6113a2c of the selected method's class, com.github.hoshikurama.ticketmanager.spigot.impls.PlatformFunctionsImpl have different Class objects for the type net.kyori.adventure.text.Component used in the signature (com.github.hoshikurama.ticketmanager.api.PlatformFunctions is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @26aaf293, parent loader java.net.URLClassLoader @4c0df1cf; com.github.hoshikurama.ticketmanager.spigot.impls.PlatformFunctionsImpl is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @6113a2c, parent loader java.net.URLClassLoader @4c0df1cf)
[16:49:04] [DefaultDispatcher-worker-2/WARN]: 	at com.github.hoshikurama.ticketmanager.spigot.impls.TMPluginImpl._init_$lambda$0(TMPluginImpl.kt:44)
[16:49:04] [DefaultDispatcher-worker-2/WARN]: 	at com.github.hoshikurama.ticketmanager.commonse.TMPlugin.enableTicketManager(TMPlugin.kt:84)
[16:49:04] [DefaultDispatcher-worker-2/WARN]: 	at com.github.hoshikurama.ticketmanager.commonse.TMPlugin$enableTicketManager$1.invokeSuspend(TMPlugin.kt)
[16:49:04] [DefaultDispatcher-worker-2/WARN]: 	at com.github.hoshikurama.ticketmanager.shaded.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[16:49:04] [DefaultDispatcher-worker-2/WARN]: 	at com.github.hoshikurama.ticketmanager.shaded.kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
[16:49:04] [DefaultDispatcher-worker-2/WARN]: 	at com.github.hoshikurama.ticketmanager.shaded.kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
[16:49:04] [DefaultDispatcher-worker-2/WARN]: 	at com.github.hoshikurama.ticketmanager.shaded.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
[16:49:04] [DefaultDispatcher-worker-2/WARN]: 	at com.github.hoshikurama.ticketmanager.shaded.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
[16:49:04] [DefaultDispatcher-worker-2/WARN]: 	at com.github.hoshikurama.ticketmanager.shaded.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
[16:49:04] [DefaultDispatcher-worker-2/WARN]: 	Suppressed: com.github.hoshikurama.ticketmanager.shaded.kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1370db32, Dispatchers.Default]

**Comment by HoshiKurama** [comment] 2024-01-11 16:05
Ahh I see, so the Spigot version will not work on Paper. 

I’m very confused why your original issue is occurring because Paper has native Kyori Adventure support, yet the plugin is erroring out because it can’t find the function to send a Kyori Component…

I’ll do more testing throughout the day, but this is a very bizarre issue to have, so it might take some time to figure this out. What are you using exactly? Paper or a fork or Paper? Also, in the meantime, definitely make sure you are on 1.18.2 because TicketManager for Paper does not support anything below that. A sure-fire way to fix the problem is to update to 1.20 if you can because TicketManager is built against that.

**Comment by XiNaru** [comment] 2024-01-11 16:07
as far as the version is concerned, all my mc servers are on paper spigot 1.18.2 so there should be no problem.

**Comment by HoshiKurama** [comment] 2024-01-11 16:10
Actually, I had a thought. Can you try updating your server to use the latest Paper 1.18.2 build? I've encountered someone having a bizarre issue pertaining to Paper's side of things in the past, and updating fixed it.

**Comment by XiNaru** [comment] 2024-01-11 16:19
okay what is the latest 1.18.2 paper?

**Comment by HoshiKurama** [comment] 2024-01-11 16:20
https://papermc.io/downloads/all click on 1.18.2 then download the top one

**Comment by XiNaru** [comment] 2024-01-11 16:23
okay now i have see all my servers dont use paper o.o i dont know why...i use cloudnet and i have choice paper lol


16:57:57] [Server thread/INFO]: This server is running CraftBukkit version 3498-Spigot-b081915-10ba1be (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)
[16:57:57] [Server thread/INFO]: Server Ping Player Sample Count: 12

**Comment by HoshiKurama** [comment] 2024-01-11 16:25
If you have the ability to upload custom server JARs, I would highly recommend doing so with the latest version of Paper, haha

**Comment by XiNaru** [comment] 2024-01-11 16:26
i do that now too, it's my own root. i wonder why he uses spigot and not paper spigot as i chose it

**Comment by XiNaru** [comment] 2024-01-11 16:28
https://images.xinaru.de/index.php/s/Sm6EtHNfbZyEw3y/preview

**Comment by HoshiKurama** [comment] 2024-01-11 16:30
That would be the latest version! Let me know if that fixes your issue

**Comment by XiNaru** [comment] 2024-01-11 16:36
now it works.

https://images.xinaru.de/index.php/s/GfN4y4qm84n6XzA/preview

**Comment by XiNaru** [comment] 2024-01-11 16:42
but a question, if i use the bungee PBE for proxy, must i add there the mysql addon too?

**Comment by HoshiKurama** [comment] 2024-01-11 16:43
Nope! The PBE is just a relay. Only have the MySQL extension on each server

**Comment by XiNaru** [comment] 2024-01-11 16:49
ah okay, and if i had actiavte proxy at all, i can ticket teleport through servers

**Comment by XiNaru** [comment] 2024-01-11 17:12
well the teleport through server dont work.

iam using cloudnet and the proxy there i only an temp server, that got deleted after server stop, and new creation.

as proxy name i hase Try Proxy
and i has try Proxy-1 (so the tasks is named) but it doesnt work


https://images.xinaru.de/index.php/s/kgsJB8o4Rz4Zmbb/preview

**Comment by HoshiKurama** [comment] 2024-01-11 17:41
It’s fine this time, but next time, please open a new issue. It just helps me keep issues in order and separate, haha.

Secondly, just to make sure things are set up correctly, did you follow the instructions [here](https://github.com/HoshiKurama/TicketManager/wiki/Proxy-Support-(TM:PBE)) for proxy setup? Emphasis on matching the name you provide in the TM:SE config file for the proxy and the name you provide the server in your bungeecord/waterfall configuration.

That error is pretty weird, so let me know once you’ve verified the above information and the issue is still happening. I fixed the proxy-related behaviour with 11.0.2, and I distinctly remember things working fine for Velocity. Just let me know.

**Comment by XiNaru** [comment] 2024-01-11 17:46
sorry


I've already read that, and I'm actually pretty sure that the proxy name is Proxy. cloudnet manages the whole thing a little differently, but everywhere I look the name says: Proxy

**Comment by HoshiKurama** [comment] 2024-01-11 17:58
Not the proxy name, the name of the server in your proxy’s configuration file. Check waterfall’s config.yml and find the server section. Those are the names you will need to use in the TM:SE config

**Comment by XiNaru** [comment] 2024-01-11 18:01
thats is the problem..in the waterfall.yml dont stands an name....

https://images.xinaru.de/index.php/s/35Cz5PFHNHweK3i/preview

**Comment by XiNaru** [comment] 2024-01-11 18:02
thats all what stands in the file from the proxy

**Comment by HoshiKurama** [comment] 2024-01-11 18:03
Check config.yml

**Comment by XiNaru** [comment] 2024-01-11 18:03
but it seems my waterfall has an error o.o


java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:395) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:301) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:287) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at de.dytanic.cloudnet.wrapper.Wrapper.lambda$startApplication$5(Wrapper.java:487) ~[wrapper.jar:3.4.5-RELEASE-0f8f0d7]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e7490f3:535]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 19 more

**Comment by XiNaru** [comment] 2024-01-11 18:05
and in the config.yml isnt an server name too hmm...

**Comment by HoshiKurama** [comment] 2024-01-11 18:07
Unfortunately I can’t help with Waterfall issues not caused by TM:PBE. I would personally recommend joining the PaperMC Discord and asking for help with your Waterfall installation.

**Comment by XiNaru** [comment] 2024-01-11 18:09
ähm what is the latest waterfall build for 1.18.2?

**Comment by XiNaru** [comment] 2024-01-11 18:10
oh wait i found on the site

**Comment by XiNaru** [comment] 2024-01-11 18:31
okay now it works,

o dont must add there PROXY i must add there the name from the underserver, where the plugin is runnig xd

**Comment by HoshiKurama** [comment] 2024-01-11 19:47
Since you resolved the issue, I am closing this issue.

**Closed as completed by HoshiKurama** 2024-01-11 19:47 UTC
